name: Send Slack Message
description: "Send slack message to a channel"
    
inputs:
  slack-webhook-url:
    description: 'Slack webhook url'
    required: true
  job-status:
    description: 'Job status'
    required: true

runs:
  using: "composite"
  steps:
    - name: send slack message
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ inputs.job-status }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url}}
