name: Build and push ngen image
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  workflow_dispatch:
  workflow_call:
    
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: ./.github/action_templates/build-and-push
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          image-name: "ngen"
          dockerfile-name: "Dockerfile.ngen"