name: Build and push final ARM image
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  workflow_dispatch:
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          architecture: [arm64]
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: ./.github/action_templates/build-and-push
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          github-sha: ${{ github.sha }}
          image-name: "ciroh-ngen-image"
          dockerfile-name: "Dockerfile"
      
