name: Build and push t-route image
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      runner_label:
        required: true
        type: string
jobs:
  build-and-push:
    runs-on: ["${{inputs.runner_label}}"]
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: ./.github/action_templates/build-and-test
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          image-name: "t-route"
          dockerfile-name: "Dockerfile.t-route"
          platform: ${{inputs.runner_label}}
        if: ${{ !startsWith(github.ref, 'refs/heads/main') }}
      - name: Build and push Docker image
        uses: ./.github/action_templates/build-and-push
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          image-name: "t-route"
          dockerfile-name: "Dockerfile.t-route"
          platform: ${{inputs.runner_label}}
        if: startsWith(github.ref, 'refs/heads/main')