name: Publish slack message
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  workflow_run:
    workflows: [Build and push deps image]
    types:
      - completed
  workflow_dispatch:

jobs:
  on-success:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Publish slack message
        uses: ./.github/action_templates/slack
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          job-status: ${{ job.status }}
          pull_request_url: ${{ github.event.pull_request.html_url }}
          head_commit_url: ${{ github.event.head_commit.url }}