name: Build and push ngen image
on:
  pull_request:
    branches: [ main, notreal ]
    paths: 
      - 'docker/Dockerfile.ngen'
      - 'docker/Dockerfile.ngen-deps'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    # For pull requests, it's not necessary to checkout code
    permissions:
      pull-requests: read
    steps:
      - name: Build ngen Docker image
        uses: ./.github/action_templates/build-and-push
        with:
          image-name: "ngen"
          dockerfile-name: "Dockerfile.ngen"      
