name: Build and push deps image
on:
  push:
    branches: [ main ]
    paths:
      - docker/**
  workflow_dispatch:
  workflow_call:
jobs:
  build-and-push:
    runs-on: self-hosted
    strategy:
      matrix:
          architecture: [arm64]
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: ./.github/action_templates/build-and-push
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          github-sha: ${{ github.sha }}
          image-name: "ngen-deps"
          dockerfile-name: "Dockerfile.ngen-deps"
          tag-name: ${{vars.TAG_NAME}}