name: Run Test
on:
  push:
    branches: [89-adding-unit-testing-for-the-pr-validation]
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ARM64
    steps:
      - name: Build and test Docker image
        uses: ./.github/action_templates/build-and-test
        with:
          docker-auth-token: ${{ secrets.DOCKER_AUTH_TOKEN }}
          image-name: "ciroh-ngen-image"
          dockerfile-name: "Dockerfile"
          platform: ARM64