name: Send Slack Message
on:
  workflow_dispatch:
    
jobs:
  send_slack:
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: ./.github/action_templates/slack
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          job-status: ${{ job.status }}
          pull_request_url: ${{ github.event.pull_request.html_url }}
          head_commit_url: ${{ github.event.head_commit.url }}